# Generated by Django 4.2.13 on 2024-08-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleconnect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibleversion',
            name='versionid',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
