# Generated by Django 4.2.13 on 2024-08-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleconnect', '0011_remove_book_chapter_chapter_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='verses',
        ),
        migrations.AddField(
            model_name='chapter',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
