# Generated by Django 4.2.13 on 2024-08-21 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibleconnect', '0014_verse_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verse',
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
