"""
Django settings for VideoWebsite project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
# from dotenv import load_dotenv

# load_dotenv()  # This loads environment variables from the .env file into the environment

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')
STATIC = os.path.join(BASE_DIR, 'static')
MEDIA_DIR = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z3tz4jgzn4*7q@gopp48i0l!u51ytp=u)qh0nv-6a&3ix4red6'

# SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = 'True'

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'bootstrap5',
    'chat',
    'blog',
    'tinymce',
    'bibleconnect',
    'notifications',
    'search',
    'user',
    'django_social_share',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.twitter',
    'person',
    'playlistapp',
    'faithgroups',
    'location_field',
    # 'datetimepicker'
    # 'location_field.apps.DefaultConfig',
    # 'django.contrib.gis',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Add this line'
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django.csrf.middleware.CsrfViewMiddleware',  # Ensure this is present

]

ROOT_URLCONF = 'VideoWebsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

WSGI_APPLICATION = 'VideoWebsite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
#
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'mydatabase',
    }
}

# settings.py
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',  # Use 'django.db.backends.mysql' for MySQL
#         'NAME': 'postgres',                       # The name of your database
#         'USER': 'mariah',                           # The database user you created
#         'PASSWORD': 'Char92513@',                   # The password for the database user
#         'HOST': '/cloudsql/still-totality-433611-n6:us-central1:disiplesapp',  # Cloud SQL instance connection name
#         'PORT': '5432',                             # PostgreSQL default port
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',

    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [STATIC, ]
MEDIA_URL = '/media/'
MEDIA_ROOT = MEDIA_DIR

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ASGI_APPLICATION = 'VideoWebsite.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('127.0.0.1', 6379)],
        },
    },
}
TINYMCE_API_KEY = '543rfms4jj6jrugypiwlj7f7q3yn8jxxe96lbfaulidklw20'
TINYMCE_JS_URL = 'https://cdn.tiny.cloud/1/543rfms4jj6jrugypiwlj7f7q3yn8jxxe96lbfaulidklw20/tinymce/7/tinymce.min.js'
TINYMCE_COMPRESSOR = False

TINYMCE_DEFAULT_CONFIG = {
    'selector': 'textarea',  # Adjust this to match your form field IDs if needed
    'plugins': 'advlist autolink lists link image charmap preview anchor searchreplace visualblocks code fullscreen insertdatetime media table paste code help wordcount',
    'toolbar': 'undo redo | formatselect | bold italic backcolor | \
        alignleft aligncenter alignright alignjustify | \
        bullist numlist outdent indent | removeformat | help',
    'height': 500,
    'menubar': False,
    'branding': False,
    'images_upload_url': '/upload/',  # Adjust this to your upload URL
    'images_upload_base_path': '/media/',  # Adjust this to your media URL
    'image_advtab': True,
    'file_picker_types': 'file image media',

    # Add your TinyMCE API key here
}
# Increase the upload size limit to 10 MB (10 * 1024 * 1024 bytes)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB

SCRIPTURE_API_KEY = 'e7e88cda842710307ea6c80947df1764'
SCRIPTURE_API_URL = 'https://api.scripture.api.bible/v1/'
CKEDITOR_UPLOAD_PATH = "uploads/"
# settings.py
CSRF_COOKIE_SECURE = False
CSRF_TRUSTED_ORIGINS = ['http://127.0.1.8000']

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Default
    'allauth.account.auth_backends.AuthenticationBackend',  # Required for allauth
]
SITE_ID = 1

GOOGLE_API_KEY = 'AIzaSyDpdlLlVUrtoNqxeEuEoEa6c9vNLHjaumE'

# LOCATION_FIELD = {
#     'provider.google.api': '//maps.google.com/maps/api/js?sensor=false',
#     # 'provider.google.api_libraries': '',
#     'provider.google.map.type': 'ROADMAP',
#     'provider.google.api_key': 'AIzaSyDpdlLlVUrtoNqxeEuEoEa6c9vNLHjaumE',
#     'search.provider': 'google',
# }
#
# LOGIN_REDIRECT_URL = '/login'
# LOGOUT_REDIRECT_URL = '/logout'
# ACCOUNT_FORMS = {'signup': 'VideoWebsite.forms.GoogleSignUpForm'}

# ACCOUNT_SIGNUP_FORM_CLASS = 'VideoWebsite.forms.GoogleSignUpForm'
# LOCATION_FIELD = {
#     'provider.openstreetmap.max_zoom': 18,
# GDAL_LIBRARY_PATH = r"C:\\Users\mariah\Desktop\GDAL\"
# GDAL_LIBRARY_PATH=r'C:\Users\mariah\Downloads\GDAL-3.9.1.win-amd64.Python37\Python\Python37\Lib\site-packages\'
