# Generated by Django 4.2.13 on 2024-08-20 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_bibleversion_versionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibleversion',
            name='books',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='connect.book'),
        ),
    ]
