# Generated by Django 4.2.13 on 2024-08-20 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibleconnect', '0003_alter_bibleversion_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibleversion',
            name='books',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='bibleconnect.book'),
            preserve_default=False,
        ),
    ]
