# Generated by Django 4.2.13 on 2024-08-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0006_alter_bibleversion_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibleversion',
            name='versionid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
