# Generated by Django 4.2.13 on 2024-08-20 22:24

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleconnect', '0007_alter_bibleversion_versionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='chapter_numbers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AddField(
            model_name='chapter',
            name='verses',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_verses', to='bibleconnect.verse'),
        ),
        migrations.AlterField(
            model_name='book',
            name='chapter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bibleconnect.chapter'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='verse_number',
            field=tinymce.models.HTMLField(),
        ),
    ]
