# Generated by Django 4.2.13 on 2024-08-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibleconnect', '0008_book_chapter_numbers_chapter_content_chapter_verses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='chapter_numbers',
            field=models.CharField(max_length=100),
        ),
    ]
