# Generated by Django 4.2.13 on 2024-08-20 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0009_alter_book_chapter_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bibleversion',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='bibleversion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='connect.bibleversion'),
        ),
    ]
