# Generated by Django 4.2.13 on 2024-08-20 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0010_remove_bibleversion_books_book_bibleversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='chapter',
        ),
        migrations.AddField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_book', to='connect.book'),
        ),
    ]
