# Generated by Django 4.2.13 on 2024-08-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0012_remove_chapter_verses_chapter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
