# Generated by Django 4.2.13 on 2024-08-21 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0015_remove_verse_chapter_delete_chapter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
