# Generated by Django 4.2.15 on 2024-08-24 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0017_book_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='Chapter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_verses', to='connect.chapter'),
        ),
    ]
