# Generated by Django 4.2.15 on 2024-08-24 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0018_verse_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='bibleversion',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verse_version', to='connect.bibleversion'),
        ),
    ]
