# Generated by Django 4.2.15 on 2024-08-24 07:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0019_verse_bibleversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='verse_text',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
