# Generated by Django 4.2.15 on 2024-08-24 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0020_alter_verse_verse_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='book',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verse_book', to='connect.book'),
        ),
    ]
