# Generated by Django 4.2.11 on 2024-08-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_messages', models.ManyToManyField(related_name='chat_messages', to='chat.message')),
            ],
        ),
    ]
