# Generated by Django 4.2.11 on 2024-08-09 01:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_alter_singlechat_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlechat',
            name='participants',
        ),
        migrations.AddField(
            model_name='singlechat',
            name='participants',
            field=models.ManyToManyField(related_name='people', to=settings.AUTH_USER_MODEL),
        ),
    ]
