# Generated by Django 4.2.13 on 2024-08-18 08:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_singlechat_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
