# Generated by Django 4.2.15 on 2024-08-31 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_group_who_can_post_groupcreationrequest_who_can_post_and_more'),
        ('chat', '0007_alter_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatrooms', to='groups.group'),
        ),
    ]
