# Generated by Django 4.2.15 on 2024-08-30 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faithgroups', '0010_grouprequest_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouprequest',
            old_name='reviewed_at',
            new_name='reviewed',
        ),
    ]
