# Generated by Django 4.2.15 on 2024-08-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='blogs',
            field=models.ManyToManyField(blank=True, through='person.BoardBlogPost', to='person.blogpost'),
        ),
        migrations.AlterField(
            model_name='board',
            name='images',
            field=models.ManyToManyField(blank=True, through='person.BoardImage', to='person.image'),
        ),
        migrations.AlterField(
            model_name='board',
            name='posts',
            field=models.ManyToManyField(blank=True, through='person.BoardPost', to='person.post'),
        ),
        migrations.AlterField(
            model_name='board',
            name='videos',
            field=models.ManyToManyField(blank=True, through='person.BoardVideo', to='person.video'),
        ),
    ]
