# Generated by Django 4.2.15 on 2024-08-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_board_blogs_alter_board_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='blogs',
            field=models.ManyToManyField(blank=True, related_name='blogs_board', through='person.BoardBlogPost', to='person.blogpost'),
        ),
        migrations.AlterField(
            model_name='board',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images_board', through='person.BoardImage', to='person.image'),
        ),
        migrations.AlterField(
            model_name='board',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='posts_board', through='person.BoardPost', to='person.post'),
        ),
        migrations.AlterField(
            model_name='board',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='videos_board', through='person.BoardVideo', to='person.video'),
        ),
    ]
