# Generated by Django 4.2.15 on 2024-08-29 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('person', '0003_alter_board_blogs_alter_board_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
