# Generated by Django 4.2.15 on 2024-08-29 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faithgroups', '0001_initial'),
        ('person', '0004_alter_podcast_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_blogpost', to='faithgroups.group'),
        ),
        migrations.AddField(
            model_name='image',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_image', to='faithgroups.group'),
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_posts', to='faithgroups.group'),
        ),
        migrations.AddField(
            model_name='video',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_videos', to='faithgroups.group'),
        ),
    ]
