# Generated by Django 4.2.15 on 2024-08-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupcreationrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupcreationrequest',
            old_name='reviewed',
            new_name='is_denied',
        ),
        migrations.AlterField(
            model_name='groupcreationrequest',
            name='group_name',
            field=models.CharField(max_length=100),
        ),
    ]
