# Generated by Django 4.2.15 on 2024-08-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faithgroups', '0003_rename_reviewed_groupcreationrequest_is_denied_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupcreationrequest',
            old_name='is_denied',
            new_name='reviewed',
        ),
    ]
