# Generated by Django 4.2.15 on 2024-08-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_rename_is_denied_groupcreationrequest_reviewed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupRequest',
        ),
    ]
