# Generated by Django 4.2.15 on 2024-08-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_grouprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='join_privacy',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='groupcreationrequest',
            name='join_privacy',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=10),
        ),
    ]
