# Generated by Django 4.2.15 on 2024-08-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithgroups', '0007_group_join_privacy_groupcreationrequest_join_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='join_privacy',
            field=models.CharField(choices=[('anyone', 'anyone can join this group automatically'), ('only_approved', 'Only users can join this group after approval')], default='public', max_length=50),
        ),
        migrations.AlterField(
            model_name='groupcreationrequest',
            name='join_privacy',
            field=models.CharField(choices=[('anyone', 'anyone can join this group automatically'), ('only_approved', 'Only users can join this group after approval')], default='public', max_length=50),
        ),
    ]
