# Generated by Django 4.2.15 on 2024-08-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_alter_group_join_privacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouprequest',
            name='reviewed_at',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='join_privacy',
            field=models.CharField(choices=[('anyone', 'automatic join'), ('only_approved', 'approval to join')], default='public', max_length=50),
        ),
        migrations.AlterField(
            model_name='groupcreationrequest',
            name='join_privacy',
            field=models.CharField(choices=[('anyone', 'automatic join'), ('only_approved', 'approval to join')], default='public', max_length=50),
        ),
    ]
