# Generated by Django 4.2.15 on 2024-08-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faithgroups', '0009_grouprequest_reviewed_at_alter_group_join_privacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouprequest',
            name='text',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
