# Generated by Django 4.2.15 on 2024-08-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_rename_reviewed_at_grouprequest_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='who_can_post',
            field=models.CharField(choices=[('members', 'all members'), ('admin_only', 'only admin')], default='members', max_length=20),
        ),
        migrations.AddField(
            model_name='groupcreationrequest',
            name='who_can_post',
            field=models.CharField(choices=[('members', 'all members'), ('admin_only', 'only admin')], default='members', max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='join_privacy',
            field=models.CharField(choices=[('anyone', 'automatic join'), ('only_approved', 'approval to join')], default='anyone', max_length=50),
        ),
        migrations.AlterField(
            model_name='groupcreationrequest',
            name='join_privacy',
            field=models.CharField(choices=[('anyone', 'automatic join'), ('only_approved', 'approval to join')], default='anyone', max_length=50),
        ),
    ]
