# Generated by Django 4.2.15 on 2024-08-31 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0012_group_who_can_post_groupcreationrequest_who_can_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', tinymce.models.HTMLField()),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('location_type', models.CharField(max_length=50)),
                ('location_details', models.CharField(max_length=200)),
                ('max_attendees', models.PositiveIntegerField(default=0)),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('webinar', 'Webinar'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('meetup', 'Meetup'), ('bible study', 'Bible Study')], max_length=20)),
                ('registration_required', models.BooleanField(default=False)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.CharField(blank=True, max_length=20, null=True)),
                ('accessibility_options', models.TextField(blank=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='event_attendees', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='groups.group')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
