# Generated by Django 4.2.15 on 2024-09-02 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_location_alter_event_location_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='accessibility_options',
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location_details',
        ),
        migrations.RemoveField(
            model_name='event',
            name='max_attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='recurrence_pattern',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_deadline',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_required',
        ),
    ]
