# Generated by Django 4.2.15 on 2024-09-03 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faithgroups', '0016_remove_event_accessibility_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='parent_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subgroups', to='faithgroups.group'),
        ),
    ]
