# Generated by Django 4.2.15 on 2024-08-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/profile_pic_blank.png', upload_to='profile_pictures/'),
        ),
    ]
